# Generated by Django 6.0.6 on 2026-06-10 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamgroup',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='team_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.teamgroup'),
        ),
    ]
